---
abstract: 'canonicalize shorthand bible references'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Religion-Bible-Reference
no_index:
  directory:
    - t
    - inc
requires:
  Sub::Exporter: 0.9
  Test::More: 0
resources:
  x_Repository: http://github.com/rjbs/religion-bible-reference
version: 0.014
